version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  atlas:
    image: sburn/apache-atlas:2.3.0
    container_name: atlas
    restart: always
    ports:
      - '21000:21000'
    environment:
      - ATLAS_HOME=/opt/atlas
      - ATLAS_OPTS=-Xmx1024m
    volumes:
      - atlas_data:/opt/atlas/data
      
  soda-core:
    image: sodadata/soda-core:latest
    container_name: opendq-soda
    working_dir: /data
    volumes:
      - ./infra/soda:/data
    entrypoint: ["tail", "-f", "/dev/null"]
    networks:
      - default

  ui:
    build:
      context: ../ui
      dockerfile: Dockerfile
    container_name: opendq-ui
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - default

  api:
    build:
      context: ../api
      dockerfile: Dockerfile.dev
    container_name: opendq-api
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - ../api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres_data:
  pgadmin_data:
  atlas_data:
